id: P1522A5BD
initial_creation_type: input
source_metadata:
  title: Tulku Rigdzin Pema
  language: bo
  description: 'Texts by and about Tulku Rigdzin Pema (sprul sku rig ''dzin padma,
    b. 1948), a ritual master connected with Shechen Monastery renowned for his expertise
    in stūpa construction and consecration:'
  volume:
    f000a6679cf142a891d482cb8d4c91ee:
      title: 'Instilling Confidence and Trust: An Inventory of the Sacred Contents
        of the Jarung Khashor Stūpa'
      parent: Inventories
created_at: '2022-03-01T01:57:31.392562'
last_modified_at: '2022-03-01T01:57:31.392565'
